# Generated by Django 6.0.3 on 2026-03-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
