# Generated by Django 6.0.3 on 2026-03-28 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
